# Site settings
author: Sascha Kala
title: Am I a software engineer yet?
header-img: img/home-bg.png
email: mxsaschakala@gmail.com
copyright_name: Sascha Kala
description: > # this means to ignore newlines until "baseurl:"
  The adventures of an aspiring tech bro
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saschakala

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
